[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]

  # Listens to your 'sine' wave AND your hardware sensors
  topics = [
    "sine",
    "s3_mini_sensorbox/sensor/+/state",
    "s3_mini_sensorbox/binary_sensor/+/state"
  ]

  data_format = "value"
  data_type = "float"

  # This tells Telegraf how to name the data in InfluxDB
  [[inputs.mqtt_consumer.topic_parsing]]
    topic = "s3_mini_sensorbox/+/+/state"
    measurement = "_/_/measurement/_"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "ih3lGQ2dVqXG7ec0Ai-flUi5ZWTqp3AChtwI0fu4014-cn5h0MRE6-RcWtlL1yYGUaaSg6NOtcW_TEjQdGGA5A=="
  organization = "leoiot"
  bucket = "server_data"