esphome:
  name: keruildr

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
# api:
  # encryption:
  #   key: "BntVVPNZbPNC5UzN9oL4XDDXj6xtatU7aVjumB4EJwY="

ota:
  password: "585353d758e3f126d2f4982f0695d956"
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Kerui LDR Hotspot"
    password: "g0MuFWdXxO2k"

web_server:
  port: 80

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_user
  password: !secret mqtt_password

captive_portal:

i2c:
  sda: 21
  scl: 22
  # scan: true
  id: bus_a

uart:
  rx_pin: GPIO13
  tx_pin: GPIO12
  baud_rate: 9600

sensor:
  - platform: bme280_i2c
    i2c_id: bus_a
    address: 0x76
    update_interval: 10s
    temperature:
      name: "Temperature"
      id: temperature
      oversampling: 16x
    pressure:
      name: "Pressure"
      id: pressure
    humidity:
      name: "Humidity"
      id: humidity

  - platform: adc
    pin: GPIO34
    name: "Illuminance"
    id: illuminance
    update_interval: 10s

  - platform: mhz19
    co2:
      name: "CO2"
      id: co2
      on_value_range:
            - below: 600.0
              then:
                - light.turn_on:
                    id: neopixel
                    brightness: 30%
                    red: 0%
                    green: 100%
                    blue: 0%    
            - above: 600.0
              below: 1000.0
              then:
                - light.turn_on:
                    id: neopixel
                    brightness: 50%
                    red: 0%
                    green: 0%
                    blue: 100%    
            - above: 1000.0
              then:
                - light.turn_on:
                    id: neopixel
                    brightness: 100%
                    red: 100%
                    green: 0%
                    blue: 0%    
    temperature:
      name: "MH-Z19 Temperature"
      id: mhz19temperature
    update_interval: 10s
    automatic_baseline_calibration: false    
binary_sensor:
  - platform: gpio
    pin: 25
    name: "Motion"
    id: motion
    device_class: motion

light:
  - platform: neopixelbus
    type: GRB
    variant: WS2812
    pin: GPIO27
    num_leds: 1
    name: "NeoPixel"
    id: neopixel
    on_turn_on:
      then:
        - light.turn_on:
            id: neopixel
            brightness: 30%
            red: 0%
            green: 0%
            blue: 1.0    

