apiVersion: 1

datasources:
  - name: InfluxDB-Flux
    type: influxdb
    access: proxy
    orgId: 1
    url: http://influxdb:8086
    isDefault: false
    editable: true

    basicAuth: true
    basicAuthUser: admin

    jsonData:
      version: Flux
      organization: leoiot
      defaultBucket: server_data
      tlsSkipVerify: false

    secureJsonData:
      token: ih3lGQ2dVqXG7ec0Ai-flUi5ZWTqp3AChtwI0fu4014-cn5h0MRE6-RcWtlL1yYGUaaSg6NOtcW_TEjQdGGA5A==
      basicAuthPassword: leogreen